### ISSUE TITLE
Add File token and captsolver.com

### ISSUE THREAD

**Issue by x1-2023** [TahaGorme/token-joiner-and-booster#1]
i have 1k token, please add file Token and add https://www.capsolver.com/

**Comment by TahaGorme** [comment]
the capsolver cannot be integrated as this project relies on an external package [discord.js-selfbot-v13](https://github.com/aiko-chan-ai/discord.js-selfbot-v13) . Create an issue [here](discord.js-selfbot-v13/issues) .

and for the file token, im adding it

**Comment by TahaGorme** [comment]
closing this since this is solved
