### ISSUE TITLE
PLS UPDATE CODE SIR

### ISSUE THREAD

**Issue by son2003010** [TahaGorme/token-joiner-and-booster#12]
discord js self bot v13 update version pls sir update source code

**Comment by kyan0045** [comment]
does it not work anymore? 
no need to update if it still works 🤷‍♂️

**Comment by son2003010** [comment]
> nó không hoạt động nữa à? không cần cập nhật nếu nó vẫn hoạt động 🤷‍♂️

Error: Unknown message. This error appears continuously

**Comment by son2003010** [comment]
It doesn't work with that self bot version anymore. Can you update to a new self bot version and new code?

**Comment by kyan0045** [comment]
Unknown message is most likely unrelated to a discord.js-selfbot-v13 update, updating now would most likely break the code and I ain't got time right now

**Comment by son2003010** [comment]
> Unknown message is most likely unrelated to a discord.js-selfbot-v13 update, updating now would most likely break the code and I ain't got time right now

thank sir
