### ISSUE TITLE
Modify the code: Change nickname, change bio, change pfp and banner of boosting account

### ISSUE THREAD

**Issue by BoyMan123Gamer** [TahaGorme/token-joiner-and-booster#14]
So i am looking to further edit this and make it change name and bio and all of the stuff mentioned in the title. I would like some support. Thanks

**Comment by kyan0045** [comment]
What do you need support with..?

**Comment by kyan0045** [comment]
You gonna respond or can I just close this?

**Comment by BoyMan123Gamer** [comment]
well i wanna understand how your code functions and so i can make my additions

**Comment by kyan0045** [comment]
Then you should read the code and make your additions...
