### ISSUE TITLE
Help how to do it

### ISSUE THREAD

**Issue by RonaldoCr71985** [TahaGorme/token-joiner-and-booster#16]
how to do it because
![Screenshot 2024-04-05 191447](https://github.com/TahaGorme/token-joiner-and-booster/assets/154416382/93a54b80-5ca5-4cb1-8a21-e8d4c780b524)
 this issue called syntaxerror

**Comment by kyan0045** [comment]
🤦‍♂️ 

[Use it in the command line](https://stackoverflow.com/a/75347796/20050681)
