### ISSUE TITLE
How do I get tokens?

### ISSUE THREAD

**Issue by MrMafia14** [TahaGorme/token-joiner-and-booster#17]
I don't know how to get nitro tokens/use them, could someone help?

**Comment by kyan0045** [comment]
You buy tokens with nitro activated, or you buy nitro.

**Comment by MrMafia14** [comment]
is there a way to use a booster tool completely free? also how do i put the tokens in them?

**Comment by MrMafia14** [comment]
them as in the bot

**Comment by kyan0045** [comment]
There isn't unless you manage to get tokens with Nitro activated on them for free
