### ISSUE TITLE
you need to update your app

### ISSUE THREAD

**Issue by vndhote** [TahaGorme/token-joiner-and-booster#6]
[ERROR] Failed to join as obi-crack kenobi#7354
DiscordAPIError: You need to update your app to join this server.
b2b02ab5-7dae-4d6f-830e-7b55634c888b
hcaptcha
RbsgH+VLi51wqlD4BIByEPrd8OFOzGbOE/0D+IyWaB7dU7Q59wtycB70D4pSmaMnVGtd34iSfNTmKiSjJNvtBa/I+2w95O/h+3QcSDWolFcTpLcBCMQTfiMpvx8=SvAKqkRLvAMWJ5tV
InJJTVNDV25pTmlIQldacXFqUkczOVp3K25FVEV5bnlnU1BmTGRkYTF1K0tsZEhqbGU2WnBvb1cwendFTkFOSlRPSlNkVXc9PWpIUjBnWXpmNGtiRXhNb2Ei.ZMy0iA.2SD-4lFqkQ_Y-B-fOZ8UEOFnYLQ

how do i fix this?

**Comment by vndhote** [comment]
![image](https://github.com/TahaGorme/token-joiner-and-booster/assets/79296613/4ed43748-3991-424a-86a4-a8095d987dbb)

**Comment by kyan0045** [comment]
Try using a different proxy
